import os
import math

import psycopg
from psycopg.rows import dict_row
from datetime import datetime, timedelta, timezone

from flask import Flask, jsonify, request
from flask_cors import CORS


app = Flask(__name__)
CORS(app)

DATABASE_URL = os.environ.get("DATABASE_URL", "")
KST = timezone(timedelta(hours=9))

QUIET_MAX_DB = 45.0
NORMAL_MAX_DB = 65.0


def get_db():
    if not DATABASE_URL:
        raise RuntimeError("Render의 환경변수 DATABASE_URL을 설정해 주세요.")
    return psycopg.connect(
        DATABASE_URL, row_factory=dict_row, connect_timeout=15,
        options="-c statement_timeout=15000",
    )


def init_db():
    with get_db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS readings (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                device_id TEXT NOT NULL,
                location_id TEXT NOT NULL,
                location_name TEXT NOT NULL,
                db DOUBLE PRECISION NOT NULL,
                lux DOUBLE PRECISION,
                temperature DOUBLE PRECISION,
                humidity DOUBLE PRECISION,
                recorded_at TIMESTAMPTZ NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_location_time
            ON readings(location_id, recorded_at)
            """
        )


def get_status(db):
    if db < QUIET_MAX_DB:
        return "quiet"
    if db < NORMAL_MAX_DB:
        return "normal"
    return "loud"


def row_to_dict(row):
    result = dict(row)
    result["recorded_at"] = result["recorded_at"].astimezone(KST).isoformat(timespec="seconds")
    result["status"] = get_status(result["db"])
    return result


@app.route("/")
def home():
    return "ESP32 환경 모니터링 서버 정상 작동!"


@app.route("/api/health", methods=["GET"])
def health():
    with get_db() as conn:
        conn.execute("SELECT 1").fetchone()
    return jsonify(
        {
            "status": "ok",
            "server_time": datetime.now(KST).isoformat(),
        }
    )


@app.route("/api/readings", methods=["POST"])
def readings():
    data = request.get_json(silent=True)
    if not isinstance(data, dict) or not data:
        return jsonify({"error": "JSON 데이터가 없습니다."}), 400

    required_fields = ["device_id", "location_id", "location_name", "db"]
    missing_fields = [field for field in required_fields if field not in data]
    if missing_fields:
        return jsonify(
            {
                "error": "필수 항목이 없습니다.",
                "missing": missing_fields,
            }
        ), 400

    for field in ("device_id", "location_id", "location_name"):
        if not isinstance(data[field], str) or not data[field].strip():
            return jsonify({"error": f"{field}는 빈 문자열이 아니어야 합니다."}), 400

    values = {}
    for field in ("db", "lux", "temperature", "humidity"):
        value = data.get(field)
        if value is None and field != "db":
            values[field] = None
            continue
        try:
            if isinstance(value, bool):
                raise ValueError
            value = float(value)
            if not math.isfinite(value):
                raise ValueError
            values[field] = value
        except (TypeError, ValueError, OverflowError):
            return jsonify({"error": f"{field}는 유효한 숫자여야 합니다."}), 400

    recorded_at = data.get("recorded_at")
    try:
        if recorded_at is None:
            recorded_at = datetime.now(KST)
        else:
            recorded_at = datetime.fromisoformat(recorded_at.replace("Z", "+00:00"))
            if recorded_at.tzinfo is None:
                recorded_at = recorded_at.replace(tzinfo=KST)
    except (TypeError, ValueError, AttributeError):
        return jsonify({"error": "recorded_at은 ISO 8601 날짜 문자열이어야 합니다."}), 400

    with get_db() as conn:
        saved = conn.execute(
            """
            INSERT INTO readings (
                device_id, location_id, location_name, db,
                lux, temperature, humidity, recorded_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (
                data["device_id"],
                data["location_id"],
                data["location_name"],
                round(values["db"], 1),
                values["lux"],
                values["temperature"],
                values["humidity"],
                recorded_at,
            ),
        ).fetchone()

    return jsonify(row_to_dict(saved)), 201


@app.route("/api/locations", methods=["GET"])
def locations():
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT r.*
            FROM readings r
            INNER JOIN (
                SELECT location_id, MAX(id) AS latest_id
                FROM readings
                GROUP BY location_id
            ) latest ON r.id = latest.latest_id
            ORDER BY r.db ASC
            """
        ).fetchall()
    return jsonify([row_to_dict(row) for row in rows])


@app.route("/api/history/<location_id>", methods=["GET"])
def history(location_id):
    try:
        hours = int(request.args.get("hours", 12))
    except ValueError:
        hours = 12

    hours = max(1, min(hours, 168))
    cutoff = datetime.now(KST) - timedelta(hours=hours)

    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT * FROM readings
            WHERE location_id = %s AND recorded_at >= %s
            ORDER BY recorded_at ASC, id ASC
            """,
            (location_id, cutoff),
        ).fetchall()
    return jsonify([row_to_dict(row) for row in rows])


@app.route("/api/recommendation", methods=["GET"])
def recommendation():
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT r.*
            FROM readings r
            INNER JOIN (
                SELECT location_id, MAX(id) AS latest_id
                FROM readings
                GROUP BY location_id
            ) latest ON r.id = latest.latest_id
            ORDER BY r.db ASC
            """
        ).fetchall()

    if not rows:
        return jsonify({"error": "최근 측정 데이터가 없습니다."}), 404

    latest_locations = [row_to_dict(row) for row in rows]
    best = min(latest_locations, key=lambda item: item["db"])
    return jsonify(
        {
            "location": best,
            "score": best["db"],
            "reason": (
                f"현재 {best['db']:.1f} dB로 측정된 공간 중 가장 조용합니다."
            ),
        }
    )


@app.cli.command("init-db")
def init_db_command():
    """Create the Neon schema before starting Gunicorn."""
    init_db()
    print("DB 테이블 준비 완료")


@app.errorhandler(psycopg.Error)
def database_error(error):
    # Do not expose credentials or raw database errors in HTTP responses/logs.
    app.logger.error("Database operation failed: %s", type(error).__name__)
    return jsonify({"error": "DB 연결 또는 처리에 실패했습니다. 잠시 후 다시 시도해 주세요."}), 503


if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "5000")), debug=False)
